# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  branches:
      only:
        - developer
    docker:
      - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    working_directory: ~/Client
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - memeStoneClient-dependencies-{{ checksum "pom.xml" }}
          - memeStoneClient-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: memeStoneClient-dependencies-{{ checksum "pom.xml" }}
  
  build-server:
    working_directory: ~/Server
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - memeStoneServer-dependencies-{{ checksum "pom.xml" }}
          - memeStoneServer-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: memeStoneServer-dependencies-{{ checksum "pom.xml" }}
        
  #test:
  #  docker:
  #    - image: circleci/openjdk:8-jdk
  #  steps:
  #    - checkout
    
workflows:
  version: 2
  build_applications:
    jobs:
      - build
      - build-server
