# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  branches:
      only: developer
    docker:
      - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    working_directory: ~/MemeStone/Client
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - memeStoneClient-dependencies-{{ checksum "pom.xml" }}
          - memeStoneClient-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: memeStoneClient-dependencies-{{ checksum "pom.xml" }}