package Websockets.Shared;

public enum MemeStoneSocketMessageOperation {
    DRAWOPERATION,
    HEALOPERATION,
    ATTACKOPERATION,
    RESSURECTOPERATION,
    NEXTTURNOPERATION,
    CONDECEOPERATION,
    SETTINGSOPERATION,
    VOLUMEOPERATION,
    DISPLAYOPERATION
}
